#!/usr/bin/env python

__author__ = "Zach Sailer"
__email__ = "zachsailer@gmail.com"

import argparse
from fetch_taxa import *

def main(input, output, email):
    """"""
    # Read an accession list from a file
    accession_list = read.read_accessions(input)

    # Fetch taxon data for that list
    xml_data = fetch(accession_list, email)

    # Parse xml data and convert to Dataframe.
    df = parse.to_DataFrame(xml_data)

    # Write to CSV
    df.to_csv(output)

if __name__ == "__main__":
    # CLI handler
    parser = argparse.ArgumentParser(description="""Reroot a phylogenetic tree on branch
        with the minimal ancestor deviation.""")
    parser.add_argument("-i", type=str, help="CSV file containing accession numbers")
    parser.add_argument("-o", type=str, help="Output CSV file.")
    parser.add_argument("--email", type=str, help="Your email address. Needed for Entrez.")

    # Parse the arguments
    args = parser.parse_args()

    # Run the main program
    main(args.i, args.o, args.email)
